FROM rust:1.78-slim AS build
WORKDIR /opt/lumen

COPY Cargo.toml rust-toolchain.toml ./
COPY crates/core/Cargo.toml crates/api/Cargo.toml crates/cluster/Cargo.toml crates/cli/Cargo.toml crates/bench/Cargo.toml ./crates/
RUN cargo fetch --locked

COPY . .
RUN cargo build --workspace --release

FROM debian:bookworm-slim
COPY --from=build /opt/lumen/target/release/lumen-cli /usr/local/bin/lumen
ENTRYPOINT ["lumen"]
